
services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: meuMenu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_PASSWORD: senha123
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  app:
    build: .
    container_name: app_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - minha_rede
    volumes:
      - ./logs:/var/log/app

volumes:
  postgres_data:

networks:
  minha_rede:
