services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network

  app:
    build: .
    container_name: app_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - auth-network

volumes:
  postgres_data:

networks:
  auth-network: