version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha_rede

  app:
    build: .
    container_name: app_container
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - minha_rede

volumes:
  postgres_data:

networks:
  minha_rede:
