spring:
  application:
    name: user-manager-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meuMenu
    username: postgres
    password: postgres