CREATE TABLE IF NOT EXISTS usuarios (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(40) UNIQUE,
    login VARCHAR(30),
    senha VARCHAR(30),
    ultima_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS clientes (
  id BIGSERIAL PRIMARY KEY REFERENCES usuarios(id)
);



